spring:
  application:
    name: user-service
  threads:
    virtual:
      enabled: true
logging:
  level:
    com.jacinthocaio: debug
server:
    port: 8090
    servlet:
      context-path: /
    error:
      include-stacktrace: on_param
    tomcat:
      threads:
        max: 20





