spring:
  application:
    name: anime-service
  threads:
    virtual:
      enabled: true
logging:
  level:
    com.jacinthocaio: debug
server:
    servlet:
      context-path: /
    error:
      include-stacktrace: on_param
    tomcat:
      threads:
        max: 20
database:
  url: ${DB_URL:localhost}:${DB_PORT:3306}
  username: ${LOCAL_USERNAME:root}
  password: ${LOCAL_USERNAME:root}




