spring:
    config:
      import: optional:classpath:.env[.properties]
    application:
      name: anime-service
    datasource:
      url: jdbc:mysql://localhost:3306/anime_service?userTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
      username: ${ENV_ROOT_USER:root}
      password: ${ENV_ROOT_PASSWORD:root}
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
    threads:
      virtual:
        enabled: true
logging:
  level:
    com.jacinthocaio: debug
server:
    servlet:
      context-path: /
    error:
      include-stacktrace: on_param
    tomcat:
      threads:
        max: 20
#database:
#  url: ${DB_URL:localhost}:${DB_PORT:3306}
#  username: ${LOCAL_USERNAME:root}
#  password: ${LOCAL_USERNAME:root}




